//! ASCII art generation at build time.
//!
//! Reads `ascii/distros/*.txt` and emits a generated Rust module with one
//! constant per logo plus a `get_ascii_art` lookup function.
//!
//! `${c1}`..`${c6}` colour placeholders in logo text are expanded at build
//! time into ANSI escapes using the per‑distro palette below. Width is
//! computed after stripping the escapes so multi‑byte ANSI doesn't break
//! probe alignment in the renderer.

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    println!("cargo:rerun-if-changed=ascii/distros/");

    let out_dir = env::var("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("ascii_art.rs");

    let ascii_dir = Path::new("ascii/distros");

    let mut code = String::new();
    code.push_str("// Auto-generated ASCII art lookup module.\n");
    code.push_str("// Generated by build.rs from ascii/distros/*.txt files.\n\n");

    let mut distros: Vec<(String, String)> = Vec::new();

    if ascii_dir.exists() {
        for entry in fs::read_dir(ascii_dir).expect("Failed to read ascii/distros directory") {
            let entry = entry.expect("Failed to read directory entry");
            let path = entry.path();
            if path.extension().is_some_and(|e| e == "txt") {
                let distro_name = path
                    .file_stem()
                    .expect("No file stem")
                    .to_string_lossy()
                    .to_lowercase();
                let content = fs::read_to_string(&path)
                    .unwrap_or_else(|_| panic!("Failed to read {:?}", path));
                distros.push((distro_name, content));
            }
        }
    }

    for (name, content) in &distros {
        let const_name = name.to_uppercase().replace('-', "_");
        let palette = distro_palette(name);
        let raw_lines: Vec<&str> = content.lines().collect();

        // Expand placeholders into ANSI escapes for each line.
        let expanded_lines: Vec<String> = raw_lines
            .iter()
            .map(|l| expand_markers(l, &palette))
            .collect();
        // Compute padding width after stripping the ANSI.
        let max_width = expanded_lines
            .iter()
            .map(|l| visible_width(l))
            .max()
            .unwrap_or(0);

        code.push_str(&format!("/// ASCII art for {}\n", name));
        code.push_str(&format!(
            "pub const ASCII_ART_{}: &[&str] = &[\n",
            const_name
        ));
        for line in &expanded_lines {
            // Pad each line's visible width up to max_width with trailing spaces.
            let pad = max_width.saturating_sub(visible_width(line));
            let padded = format!("{line}{}", " ".repeat(pad));
            code.push_str(&format!("    {:?},\n", padded));
        }
        code.push_str("];\n\n");
        code.push_str(&format!(
            "pub const ASCII_ART_{}_WIDTH: usize = {};\n\n",
            const_name, max_width
        ));
    }

    code.push_str("/// Get ASCII art for a given distro name.\n");
    code.push_str("/// Returns the art lines and the maximum display width.\n");
    code.push_str("pub fn get_ascii_art(distro: &str) -> (&'static [&'static str], usize) {\n");
    code.push_str("    let distro_lower = distro.to_lowercase();\n");

    let generic_names = ["linux", "macos", "windows"];
    let mut specific_distros: Vec<&(String, String)> = distros
        .iter()
        .filter(|(name, _)| !generic_names.contains(&name.as_str()))
        .collect();
    let mut generic_distros: Vec<&(String, String)> = distros
        .iter()
        .filter(|(name, _)| generic_names.contains(&name.as_str()))
        .collect();
    // Longest names first so e.g. "ubuntu-mate" matches before "ubuntu".
    specific_distros.sort_by(|a, b| b.0.len().cmp(&a.0.len()).then(a.0.cmp(&b.0)));
    generic_distros.sort_by(|a, b| a.0.cmp(&b.0));

    for (name, _) in specific_distros {
        let const_name = name.to_uppercase().replace('-', "_");
        // Match against the original name with - in it too, e.g. "ubuntu-mate".
        let match_key = name.replace('_', "-");
        code.push_str(&format!(
            "    if distro_lower.contains(\"{}\") {{\n",
            match_key
        ));
        code.push_str(&format!(
            "        return (ASCII_ART_{}, ASCII_ART_{}_WIDTH);\n",
            const_name, const_name
        ));
        code.push_str("    }\n");
    }
    for (name, _) in generic_distros {
        let const_name = name.to_uppercase().replace('-', "_");
        code.push_str(&format!("    if distro_lower.contains(\"{}\") {{\n", name));
        code.push_str(&format!(
            "        return (ASCII_ART_{}, ASCII_ART_{}_WIDTH);\n",
            const_name, const_name
        ));
        code.push_str("    }\n");
    }

    code.push_str("    #[cfg(target_os = \"linux\")]\n");
    code.push_str("    return (ASCII_ART_LINUX, ASCII_ART_LINUX_WIDTH);\n");
    code.push_str("    #[cfg(target_os = \"macos\")]\n");
    code.push_str("    return (ASCII_ART_MACOS, ASCII_ART_MACOS_WIDTH);\n");
    code.push_str("    #[cfg(target_os = \"windows\")]\n");
    code.push_str("    return (ASCII_ART_WINDOWS, ASCII_ART_WINDOWS_WIDTH);\n");
    code.push_str("    #[cfg(not(any(target_os = \"linux\", target_os = \"macos\", target_os = \"windows\")))]\n");
    code.push_str("    return (ASCII_ART_LINUX, ASCII_ART_LINUX_WIDTH);\n");
    code.push_str("}\n");

    fs::write(&dest_path, code).expect("Failed to write generated ascii_art.rs");
}

/// 256-colour palette for `${c1}`..`${c6}` placeholders, per distro.
///
/// Mostly mirrors neofetch's `set_colors` defaults. Pick something readable
/// if the distro isn't listed.
fn distro_palette(name: &str) -> [u8; 6] {
    // (c1, c2, c3, c4, c5, c6) — 256-colour codes.
    match name {
        // Existing logos in repo:
        "ubuntu" => [208, 15, 7, 7, 7, 7],
        "arch" => [6, 7, 6, 6, 6, 6],
        "fedora" | "fedora_silverblue" | "fedora-silverblue" => [4, 7, 4, 4, 4, 4],
        "debian" => [1, 7, 3, 3, 3, 3],
        "nixos" => [4, 6, 4, 4, 4, 4],
        "macos" => [2, 3, 1, 5, 4, 4],
        "windows" => [4, 6, 4, 4, 4, 4],
        "linux" => [7, 8, 3, 7, 7, 7],

        // Ported logos:
        "manjaro" => [2, 7, 2, 2, 2, 2],
        "mint" | "linuxmint" => [2, 7, 2, 2, 2, 2],
        "popos" | "pop_os" | "pop-os" => [6, 7, 6, 6, 6, 6],
        "kali" => [4, 8, 4, 4, 4, 4],
        "gentoo" => [5, 7, 5, 5, 5, 5],
        "void" => [2, 0, 2, 2, 2, 2],
        "alpine" => [4, 7, 4, 4, 4, 4],
        "opensuse" | "opensuse_tumbleweed" | "opensuse_leap" => [2, 7, 2, 2, 2, 2],
        "raspbian" => [1, 2, 1, 1, 1, 1],
        "elementary" => [7, 6, 7, 7, 7, 7],
        "rocky" => [2, 7, 2, 2, 2, 2],
        "alma" | "almalinux" => [1, 7, 3, 4, 5, 6],
        "endeavouros" | "endeavour" => [5, 4, 1, 5, 5, 5],
        "garuda" => [3, 7, 3, 3, 3, 3],
        "asahi" => [5, 7, 5, 5, 5, 5],
        "artix" => [6, 7, 6, 6, 6, 6],
        "centos" => [3, 5, 4, 2, 7, 7],
        "deepin" => [6, 7, 6, 6, 6, 6],
        "devuan" => [5, 7, 5, 5, 5, 5],
        "freebsd" => [1, 7, 1, 1, 1, 1],
        "openbsd" => [3, 7, 6, 1, 7, 7],
        "netbsd" => [5, 7, 5, 5, 5, 5],
        "kde_neon" | "kde-neon" | "neon" => [6, 7, 6, 6, 6, 6],
        "kubuntu" => [4, 7, 4, 4, 4, 4],
        "lubuntu" => [4, 7, 4, 4, 4, 4],
        "xubuntu" => [4, 7, 4, 4, 4, 4],
        "ubuntu_mate" | "ubuntu-mate" => [2, 7, 2, 2, 2, 2],
        "ubuntu_budgie" | "ubuntu-budgie" => [6, 7, 6, 6, 6, 6],
        "mx" | "mxlinux" => [7, 0, 7, 7, 7, 7],
        "parrot" => [6, 7, 6, 6, 6, 6],
        "peppermint" => [1, 7, 1, 1, 1, 1],
        "qubes" => [4, 7, 4, 4, 4, 4],
        "slackware" => [4, 7, 4, 4, 4, 4],
        "solus" => [4, 7, 4, 4, 4, 4],
        "steamos" => [5, 7, 5, 5, 5, 5],
        "tails" => [5, 7, 5, 5, 5, 5],
        "zorin" => [4, 7, 4, 4, 4, 4],
        "arcolinux" | "arco" => [4, 6, 4, 4, 4, 4],
        "archcraft" => [6, 7, 6, 6, 6, 6],
        "archlabs" => [4, 6, 4, 4, 4, 4],
        "blackarch" => [1, 7, 1, 1, 1, 1],
        "cachyos" => [6, 7, 6, 6, 6, 6],
        "crystal" => [6, 7, 6, 6, 6, 6],
        "guix" => [3, 5, 3, 3, 3, 3],
        "haiku" => [3, 7, 3, 3, 3, 3],
        "lite" | "linuxlite" => [3, 7, 3, 3, 3, 3],
        "mageia" => [4, 7, 4, 4, 4, 4],
        "oracle" => [1, 7, 1, 1, 1, 1],
        "redhat" | "rhel" => [1, 7, 1, 1, 1, 1],
        "ubuntu_studio" | "ubuntu-studio" => [4, 7, 4, 4, 4, 4],
        "vanilla" | "vanillaos" => [3, 7, 3, 3, 3, 3],

        _ => [4, 7, 4, 4, 4, 4], // default blue + white
    }
}

/// Replace `${c1}`..`${c6}` placeholders in a single line with the matching
/// 256-colour ANSI escape sequence. Returns the expanded line with a trailing
/// SGR reset so colour can't bleed past the line.
fn expand_markers(line: &str, palette: &[u8; 6]) -> String {
    if !line.contains("${c") {
        return line.to_string();
    }
    let mut out = String::with_capacity(line.len() + 16);
    let mut chars = line.chars().peekable();
    while let Some(c) = chars.next() {
        if c == '$' && chars.peek() == Some(&'{') {
            chars.next();
            let mut tag = String::new();
            while let Some(&next) = chars.peek() {
                chars.next();
                if next == '}' {
                    break;
                }
                tag.push(next);
            }
            if let Some(idx_str) = tag.strip_prefix('c')
                && let Ok(idx) = idx_str.parse::<usize>()
                && (1..=6).contains(&idx)
            {
                out.push_str(&format!("\x1b[38;5;{}m", palette[idx - 1]));
            }
        } else {
            out.push(c);
        }
    }
    out.push_str("\x1b[0m");
    out
}

/// Display width of a line after stripping ANSI escape sequences. Used in
/// build.rs so we don't have to depend on the unicode-width crate at build
/// time; assumes the ASCII art is all single-cell width characters.
fn visible_width(s: &str) -> usize {
    let mut count = 0usize;
    let mut chars = s.chars().peekable();
    while let Some(c) = chars.next() {
        if c == '\x1b' && chars.peek() == Some(&'[') {
            chars.next();
            while let Some(&next) = chars.peek() {
                chars.next();
                if next.is_ascii_alphabetic() {
                    break;
                }
            }
            continue;
        }
        count += 1;
    }
    count
}
