//! ASCII art generation at build time.
//!
//! This build script reads ASCII art text files from the `ascii/distros/` directory
//! and generates a Rust source file containing a lookup function for distro logos.

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    println!("cargo:rerun-if-changed=ascii/distros/");

    let out_dir = env::var("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("ascii_art.rs");

    let ascii_dir = Path::new("ascii/distros");

    let mut code = String::new();

    // Generate module documentation
    code.push_str("// Auto-generated ASCII art lookup module.\n");
    code.push_str("// Generated by build.rs from ascii/distros/*.txt files.\n\n");

    // Collect all ASCII art files
    let mut distros: Vec<(String, String)> = Vec::new();

    if ascii_dir.exists() {
        for entry in fs::read_dir(ascii_dir).expect("Failed to read ascii/distros directory") {
            let entry = entry.expect("Failed to read directory entry");
            let path = entry.path();

            if path.extension().is_some_and(|e| e == "txt") {
                let distro_name = path
                    .file_stem()
                    .expect("No file stem")
                    .to_string_lossy()
                    .to_lowercase();

                let content = fs::read_to_string(&path)
                    .unwrap_or_else(|_| panic!("Failed to read {:?}", path));

                distros.push((distro_name, content));
            }
        }
    }

    // Generate the ASCII art constants
    for (name, content) in &distros {
        let const_name = name.to_uppercase().replace('-', "_");
        let lines: Vec<&str> = content.lines().collect();
        let max_width = lines.iter().map(|l| l.len()).max().unwrap_or(0);

        code.push_str(&format!("/// ASCII art for {}\n", name));
        code.push_str(&format!(
            "pub const ASCII_ART_{}: &[&str] = &[\n",
            const_name
        ));

        for line in &lines {
            // Pad lines to consistent width
            code.push_str(&format!(
                "    {:?},\n",
                format!("{:width$}", line, width = max_width)
            ));
        }

        code.push_str("];\n\n");

        // Generate width constant
        code.push_str(&format!(
            "pub const ASCII_ART_{}_WIDTH: usize = {};\n\n",
            const_name, max_width
        ));
    }

    // Generate the lookup function
    code.push_str("/// Get ASCII art for a given distro name.\n");
    code.push_str("/// Returns the art lines and the width of the widest line.\n");
    code.push_str("/// Falls back to generic Linux art if distro is not found.\n");
    code.push_str("pub fn get_ascii_art(distro: &str) -> (&'static [&'static str], usize) {\n");
    code.push_str("    let distro_lower = distro.to_lowercase();\n");
    code.push_str("    \n");

    // Generate match arms for each distro with aliases
    // Sort distros: specific ones first, generic OS names (linux, macos, windows) last
    code.push_str("    // Match distro name (with common aliases)\n");
    code.push_str("    // Note: More specific distros are checked before generic OS names\n");

    // Separate generic OS names from specific distros
    let generic_names = ["linux", "macos", "windows"];
    let mut specific_distros: Vec<&(String, String)> = distros
        .iter()
        .filter(|(name, _)| !generic_names.contains(&name.as_str()))
        .collect();
    let mut generic_distros: Vec<&(String, String)> = distros
        .iter()
        .filter(|(name, _)| generic_names.contains(&name.as_str()))
        .collect();

    // Sort alphabetically within each group
    specific_distros.sort_by(|a, b| a.0.cmp(&b.0));
    generic_distros.sort_by(|a, b| a.0.cmp(&b.0));

    // Generate match arms: specific distros first
    for (name, _) in specific_distros {
        let const_name = name.to_uppercase().replace('-', "_");
        code.push_str(&format!("    if distro_lower.contains(\"{}\") {{\n", name));
        code.push_str(&format!(
            "        return (ASCII_ART_{}, ASCII_ART_{}_WIDTH);\n",
            const_name, const_name
        ));
        code.push_str("    }\n");
    }

    // Then generic OS names as fallback
    for (name, _) in generic_distros {
        let const_name = name.to_uppercase().replace('-', "_");
        code.push_str(&format!("    if distro_lower.contains(\"{}\") {{\n", name));
        code.push_str(&format!(
            "        return (ASCII_ART_{}, ASCII_ART_{}_WIDTH);\n",
            const_name, const_name
        ));
        code.push_str("    }\n");
    }

    // Fallback
    code.push_str("    \n");
    code.push_str("    // Fallback to Linux generic art\n");
    code.push_str("    #[cfg(target_os = \"linux\")]\n");
    code.push_str("    return (ASCII_ART_LINUX, ASCII_ART_LINUX_WIDTH);\n");
    code.push_str("    \n");
    code.push_str("    #[cfg(target_os = \"macos\")]\n");
    code.push_str("    return (ASCII_ART_MACOS, ASCII_ART_MACOS_WIDTH);\n");
    code.push_str("    \n");
    code.push_str("    #[cfg(target_os = \"windows\")]\n");
    code.push_str("    return (ASCII_ART_WINDOWS, ASCII_ART_WINDOWS_WIDTH);\n");
    code.push_str("    \n");
    code.push_str("    #[cfg(not(any(target_os = \"linux\", target_os = \"macos\", target_os = \"windows\")))]\n");
    code.push_str("    return (ASCII_ART_LINUX, ASCII_ART_LINUX_WIDTH);\n");
    code.push_str("}\n");

    // Write the generated code
    fs::write(&dest_path, code).expect("Failed to write generated ascii_art.rs");
}
