use console::Color;

#[cfg(target_os = "windows")]
pub const ASCII_ART: [&str; 16] = [
    "WWWWWWWWWWWWWW  WWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWW  WWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWW  WWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWW  WWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWW  WWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWW  WWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWW  WWWWWWWWWWWWWW",
    "                              ",
    "WWWWWWWWWWWWWW  WWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWW  WWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWW  WWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWW  WWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWW  WWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWW  WWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWW  WWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWW  WWWWWWWWWWWWWW",
];
#[cfg(target_os = "windows")]
pub const ASCII_ART_FILLER: &str = "                              ";

// TODO: Add ASCII art for Linux and macOS
